services:
  - type: web
    name: club-digital-pro-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MP_ACCESS_TOKEN
        sync: false
      - key: FRONTEND_URL
        value: https://frontend-indol-rho-38.vercel.app
      - key: NODE_ENV
        value: production
      - key: GCLOUD_PROJECT
        value: club-newbery-digital
